server:
  port: 8081
  servlet:
    context-path: /crud

spring:
    application:
      name: crud
    jpa:
      database-platform=org:
        hibernate:
          dialect:
            MySQL8Dialect:
      show-sql: true
      open-in-view: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
    jmx:
      enabled: false
    datasource:
      url: jdbc:mysql://localhost:3306/crud?createDatabaseIfNotExist=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo
      username: root
      password: root

    rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: admin

crud:
  rabbitmq:
    exchange: crud.exchange
    routingKey: crud.produto.routingKey

security:
  jwt:
    token:
      secret-key: chave_microservicos

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka
